### ISSUE TITLE
Failed to render time.

### ISSUE THREAD

**Issue by buckett** [marlonlom/timeago#25]
When attempting to calculate a nice time ago I got (v4.0.1):
```
java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	at com.github.marlonlom.utilities.timeago.TimeAgo$Companion.using(TimeAgo.kt) ~[timeago-4.0.1.jar:na]
	at com.github.marlonlom.utilities.timeago.TimeAgo$Companion.using$default(TimeAgo.kt:249) ~[timeago-4.0.1.jar:na]
	at com.github.marlonlom.utilities.timeago.TimeAgo.using(TimeAgo.kt) ~[timeago-4.0.1.jar:na]
```

Downgrading to v3.0.2 fixed the issue.

**Comment by marlonlom** [comment]
@buckett  It got fixed in newer versions. closing this one.

**Comment by buckett** [comment]
I don't see a newer version than 4.0.1, is this only fixed in master?
